from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable

import numpy as np


@runtime_checkable
class EnvPlugin(Protocol):
    def env_id(self) -> str: ...
    def configure(self, config: dict[str, Any]) -> None: ...

    def reset(self, seed: int | None = None) -> dict[str, Any]:
        """Reset environment. seed is for env-internal state only (e.g. randomizing
        start position). Global RNG seeding is handled by the runner."""
        ...

    def step(self, action: np.ndarray) -> tuple[dict, float, bool, dict]: ...
    def get_car_state(self) -> dict[str, Any]: ...
    def get_progress(self) -> float: ...


@runtime_checkable
class WorldModelPlugin(Protocol):
    @property
    def raster_size(self) -> int: ...
    @property
    def aux_dim(self) -> int: ...
    def model_id(self) -> str: ...
    def load(self, weights_path: str, device: str = "cpu") -> None: ...
    def encode(self, obs: dict[str, Any]) -> Any: ...
    def encode_target(self, obs: dict[str, Any]) -> Any: ...
    def predict(self, latent: Any, action: np.ndarray) -> Any: ...
    def predict_progress(self, latent: Any) -> float: ...
    def predict_offtrack(self, latent: Any) -> float: ...
    def get_raw_model(self) -> Any: ...


@runtime_checkable
class PlannerPlugin(Protocol):
    def planner_id(self) -> str: ...
    def configure(self, config: dict[str, Any], world_model: WorldModelPlugin) -> None: ...
    def reset(self) -> None: ...
    def act(self, obs: dict[str, Any], car_state: dict[str, Any] | None = None) -> np.ndarray: ...


@runtime_checkable
class MetricPlugin(Protocol):
    def metric_id(self) -> str: ...
    def higher_is_better(self) -> bool: ...
    def compute(self, episodes: list[dict[str, Any]]) -> dict[str, Any]: ...


@runtime_checkable
class SignalTranslator(Protocol):
    """Translates raw step data into human-readable named signals."""

    def signal_names(self) -> list[str]: ...

    def translate_step(
        self, step: dict[str, Any], prev_velocity: float | None = None
    ) -> dict[str, float]: ...

    # Optional (checked via hasattr at call sites)
    def signal_schema(self) -> "SignalSchema": ...  # type: ignore[name-defined]  # noqa: F821

    def analyze_segment(
        self,
        signals_a: dict[int, dict[str, float]],
        signals_b: dict[int, dict[str, float]],
        step: int,
        window_half: int = 5,
    ) -> list[tuple[str, str]]: ...

    def format_live_pair(self, frame: Any) -> Any: ...


@runtime_checkable
class PanelProvider(Protocol):
    """Provides a custom TUI panel for adapter-specific visualization."""

    def panel_id(self) -> str: ...

    def panel_label(self) -> str: ...


@runtime_checkable
class AdapterFactory(Protocol):
    """Factory for creating environment, world model, planner, and metric instances."""
    def bind_repo(self, repo: Path) -> None: ...
    def create_env(self, config: dict[str, Any]) -> EnvPlugin: ...
    def create_world_model(self, weights_path: str, device: str = "cpu") -> WorldModelPlugin: ...
    def create_planner(self, config: dict[str, Any], world_model: WorldModelPlugin) -> PlannerPlugin: ...
    def get_metrics(self) -> list[MetricPlugin]: ...

    # Discovery & defaults for interactive setup
    def discover_weights(self, repo: Path) -> list[dict[str, Any]]:
        """Scan repo for available weight files.
        Returns list of dicts with keys: name, path, size_mb, mtime."""
        ...

    def discover_envs(self, repo: Path) -> list[str]:
        """Scan repo for available environment configs/scenarios.
        For F1: track names. For robotics: scene configs. Returns sorted names."""
        ...

    def default_planner_config(self) -> dict[str, Any]:
        """Return default planner config dict for thesean runs."""
        ...

    def default_env_config(self, env_id: str, world_model: WorldModelPlugin | None = None) -> dict[str, Any]:
        """Return full env config dict for a given env ID (e.g. track name).
        The env_id comes from discover_envs(). If world_model is provided,
        raster_size is inferred from checkpoint weights."""
        ...

    # Optional extended methods (Phase 3) — checked via hasattr at call sites
    def detect_project(self, repo: Path) -> dict[str, Any]:
        """Scan repo and return discovered project assets. Optional."""
        ...

    def get_signal_translator(self) -> SignalTranslator | None:
        """Return a signal translator for human-readable step data. Optional."""
        ...

    def get_panel_providers(self) -> list[PanelProvider]:
        """Return custom panel providers for TUI visualization. Optional."""
        ...
